name: everyday_quotes
description: Random beautiful quotes.

version: 3.0.0+3

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: "0.13.3+3"
  http: "0.12.0"
  flushbar: ^1.2.1
  share: ^0.6.1
  splashscreen: ^1.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

flutter_icons:
  android: true 
  ios: true
  image_path: "logo.png"

assets:
  -Quotes_logo.png